# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests, e.g. python setup.py test
script:
  - make deps
  - make test
  - make coverage
  - make lint

after_success: coveralls
